"""create rank on Item and admin on User

Revision ID: c5ce2fa5e3b6
Revises: 382276a69291
Create Date: 2024-01-18 14:21:11.916265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ce2fa5e3b6'
down_revision: Union[str, None] = '382276a69291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('revoked', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('rank', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'items', ['topic_id', 'rank'], deferrable='True')
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_column('items', 'rank')
    op.drop_column('access_tokens', 'revoked')
    # ### end Alembic commands ###
