"""remove constraint on rank and topic id for item table

Revision ID: 0f7181bb8f64
Revises: 0f8acc6fc003
Create Date: 2024-02-01 13:46:54.356372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7181bb8f64'
down_revision: Union[str, None] = '0f8acc6fc003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_topic_id_rank_key', 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('items_topic_id_rank_key', 'items', ['topic_id', 'rank'])
    # ### end Alembic commands ###
