"""create cascade deletion for topics hierarchy

Revision ID: 0f8acc6fc003
Revises: 63a8101fc2d8
Create Date: 2024-01-24 14:40:53.863116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8acc6fc003'
down_revision: Union[str, None] = '63a8101fc2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'topics', ['content', 'parent_topic_id'])
    op.drop_constraint('topics_parent_topic_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'topics', ['parent_topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_parent_topic_id_fkey', 'topics', 'topics', ['parent_topic_id'], ['id'])
    op.drop_constraint(None, 'topics', type_='unique')
    # ### end Alembic commands ###
